name: Create wasm and push to web branch

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Main Branch
      uses: actions/checkout@v3

    - name: Cache Dependencies
      uses: ./.github/actions/cache
      with:
        cache-key: build-and-publish

    - name: Install Rust Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: wasm32-unknown-unknown
        profile: minimal
        override: true

    - name: Add Cargo Bin to PATH
      run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Install wasm-bindgen-cli
      run: cargo install wasm-bindgen-cli

    - name: Build WASM
      run: |
        cargo build --release --target wasm32-unknown-unknown
        wasm-bindgen --no-typescript --target web --out-dir ./out/ --out-name "snakex" ./target/wasm32-unknown-unknown/release/snakex.wasm

    - name: List Output Files
      run: ls -al ./out/

    - name: Checkout Output Branch
      uses: actions/checkout@v3
      with:
        ref: web
        path: web-branch
        fetch-depth: 0

    - name: Copy Output Files to Root of Output Branch
      run: |
        cp -r ./out/* web-branch/

    - name: Commit and Push to Output Branch
      run: |
        cd web-branch
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add .
        git diff --quiet || git commit -m "Update WASM output files"
        git push origin HEAD:web

    - name: Clean Up Post-Job
      if: always()
      run: rm -rf web-branch
