name: Create wasm and push to web branch

on:
  push:
    branches:
      - main

jobs:
  run-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Main Branch
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: wasm32-unknown-unknown
        profile: minimal
        override: true

    - name: Build WASM
      run: |
        cargo build --release --target wasm32-unknown-unknown
        wasm-bindgen --no-typescript --target web --out-dir ./out/ --out-name "snakex" ./target/wasm32-unknown-unknown/release/snakex.wasm


    - name: Checkout Output Branch
      uses: actions/checkout@v2
      with:
        ref: 'web'

    - name: Copy Output Files
      run: |
        cp -r ./out/* .

    - name: Commit and Push
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add .
        git commit -m "Update WASM output files"
        git push origin HEAD:web